swagger: '2.0'

info:
  title: FireCloud
  description: |
    Genome analysis execution service.
  version: "0.0.1"
  license:
    name: BSD
    url: http://opensource.org/licenses/BSD-3-Clause
  termsOfService: https://github.com/broadinstitute/firecloud-orchestration

# TODO(dmohs): Don't do this.
host: %s
basePath: /api

paths:
  /workspaces:
    get:
      tags:
      - workspaces
      operationId: listWorkspaces
      summary: |
        Lists workspaces.
      produces:
      - application/json
      - text/plain
      responses:
        200:
          description: List of workspaces.
