swagger: '2.0'

info:
  title: FireCloud
  description: |
    Genome analysis execution service.
  version: "0.0.1"
  license:
    name: BSD
    url: http://opensource.org/licenses/BSD-3-Clause
  termsOfService: https://github.com/broadinstitute/firecloud-orchestration

basePath: /api

paths:
  /workspaces:
    get:
      tags:
      - workspaces
      operationId: listWorkspaces
      summary: |
        Lists workspaces.
      produces:
      - application/json
      - text/plain
      responses:
        200:
          description: List of workspaces.
  /methods:
    get:
      tags:
      - Method Repository
      operationId: listMethodRepositoryMethods
      summary: |
        Lists Method Repository methods.
      produces:
      - application/json
      responses:
        200:
          description: List of Method Repository methods.
  /configurations:
    get:
      tags:
      - Method Repository
      operationId: listMethodRepositoryConfigurations
      summary: |
        List Method Repository configurations.
      produces:
      - application/json
      responses:
        200:
          description: List of Method Repository configurations.
  /workspaces/{workspaceNamespace}/{workspaceName}/submissions:
    get:
      tags:
      - Submissions
      operationId: listSubmissions
      summary: |
        List submissions.
      produces:
      - application/json
      parameters:
        - name: workspaceNamespace
          description: Workspace Namespace
          required: true
          type: string
          in: path
        - name: workspaceName
          description: Workspace Name
          required: true
          type: string
          in: path
      responses:
        200:
          description: List of submissions
        404:
          description: Workspace not found
        500:
          description: Internal Error
    post:
      tags:
      - Submissions
      operationId: createSubmission
      summary: |
        Create a submission.
      produces:
      - application/json
      parameters:
        - name: workspaceNamespace
          description: Workspace Namespace
          required: true
          type: string
          in: path
        - name: workspaceName
          description: Workspace Name
          required: true
          type: string
          in: path
        - name: submission
          description: Post Submission
          required: true
          type: string
          in: body
          schema:
            $ref: SubmissionIngest
      responses:
        201:
          description: Successful Request
        400:
          description: Expression eval failed or entities are not of type required by method config
        404:
          description: Method Configuration or Entity not found
        409:
          description: Method Configuration failed to resolve input expressions with the supplied Entity
        500:
          description: Internal Error
  /workspaces/{workspaceNamespace}/{workspaceName}/submissions/{submissionId}:
    get:
      tags:
      - Submissions
      operationId: monitorSubmission
      summary: |
        Monitor submission status
      produces:
      - application/json
      parameters:
        - name: workspaceNamespace
          description: Workspace Namespace
          required: true
          type: string
          in: path
        - name: workspaceName
          description: Workspace Name
          required: true
          type: string
          in: path
        - name: submissionId
          description: Submission ID
          required: true
          type: string
          in: path
      responses:
        200:
          description: monitor a submission status
        404:
          description: Submission not found
        500:
          description: Internal Error
  /workspaces/{workspaceNamespace}/{workspaceName}/submissions/{submissionId}/workflows/{workflowId}/outputs:
    get:
      tags:
      - Submissions
      operationId: workflowOutputsInSubmission
      summary: |
        Get workflow outputs.
      produces:
      - application/json
      parameters:
        - name: workspaceNamespace
          description: Workspace Namespace
          required: true
          type: string
          in: path
        - name: workspaceName
          description: Workspace Name
          required: true
          type: string
          in: path
        - name: submissionId
          description: Submission ID
          required: true
          type: string
          in: path
        - name: workflowId
          description: Workflow ID
          required: true
          type: string
          in: path
      responses:
        200:
          description: Get workflow outputs
        404:
          description: Submission or Workflow not found
        500:
          description: Internal Error

definitions:
  SubmissionIngest:
    properties:
      methodConfigurationNamespace:
        type: string
      methodConfigurationName:
        type: string
      entityType:
        type: string
      entityName:
        type: string
      expression:
        type: string
    required:
      - methodConfigurationNamespace
      - methodConfigurationName
      - entityType
      - entityName