version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    reviewers:
      - "@broadinstitute/broad-core-services"
    commit-message:
      prefix: "[CORE-69]"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    groups:
      artifact-actions:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
