jdk:
  - oraclejdk8

sudo: required
dist: trusty

language: scala

scala:
  - 2.11.12

script: AGORA_URL_ROOT='http://localhost:8989' RAWLS_URL_ROOT='http://localhost:8990' THURLOE_URL_ROOT='http://localhost:8991' FIRE_CLOUD_ID='123' sbt coverage test coverageReport

after_success: sbt coveralls

notifications:
  email: false

# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html describes how to enable caches for sbt dependencies
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
