methods {
  authPrefix="/api/v1"
}

workspace {
  model="model.json"
  authPrefix="/api"
  workspacesPath="/workspaces"
  workspacesV2Path="/workspaces/v2"
  workspacesAclPath="/workspaces/%s/%s/acl"
  entitiesPath="/workspaces/%s/%s/entities"
  entityQueryPath="/workspaces/%s/%s/entityQuery"
  importEntitiesPath="/workspaces/%s/%s/importEntities"
  workspacesEntitiesCopyPath="/workspaces/entities/copy"
  submissionsPath="/workspaces/%s/%s/submissions"
  submissionsCountPath="/workspaces/%s/%s/submissionsCount"
  submissionsIdPath="/workspaces/%s/%s/submissions/%s"
  submissionsWorkflowIdPath="/workspaces/%s/%s/submissions/%s/workflows/%s"
  submissionsWorkflowIdOutputsPath="/workspaces/%s/%s/submissions/%s/workflows/%s/outputs"
  adminAlterGroupMembershipPath="/admin/groups/%s/members"
  alterGroupMembershipPath="/groups/%s/%s/%s"
  createGroup="/groups/%s"
  overwriteGroupMembershipPath="/groups/%s/%s"
  executionEngineVersionPath="/version/executionEngine"
  notificationsPath="/notifications"
}

cromiam {
  authPrefix="/api"
}

rawls {
  defaultPageSize = 500
}

userprofile {
  authPrefix = "/api"
  setKey="/thurloe"
  get="/thurloe/%s/%s"
  getAll="/thurloe/%s"
  getQuery="/thurloe"
  delete="/thurloe/%s/%s"
  validPreferenceKeyPrefixes=["notifications/"]
  validPreferenceKeys=["starredWorkspaces"]
}

googlecloud {
  storagePriceList = {
    "STANDARD": 0.02,
    "NEARLINE": 0.01,
    "COLDLINE": 0.004,
    "ARCHIVE": 0.0012,
    "REGIONAL": 0.02,
    "MULTI_REGIONAL": 0.026
  }

  # egress key previouly was "CP-COMPUTEENGINE-INTERNET-EGRESS-NA-NA"
  priceListEgressKey = "CP-INTERNET-EGRESS-STANDARD-TIER-FROM-NA"
  priceListStorageKey = "CP-BIGSTORE-STANDARD"
}

firecloud {
  max-filematching-bucket-files = 25000
}

sam {
  groupResourceType = "managed-group"
  groupMemberPolicy = "member"
  # at the time of writing each orch instance handles 15 rps max, let them make concurrent sam requests
  # this is probably overkill because 15 rps is not the same as 15 concurrent requests
  # orch's average latency is 226ms, so probabaly 4 concurrent requests is what orch handles and only a fraction of those are sam's part
  maxConcurrentRequests = 15
}

elasticsearch {
  libraryEnabled = false
}

nih {
  # NIH prohibits accounts from free email providers or emails from contries of concern
  # (?i) is case insensitive
  denyEmailPatterns = [
    "(?i).+@(.+\\.)*126\\..+",
    "(?i).+@(.+\\.)*163\\..+",
    "(?i).+@(.+\\.)*aol\\..+",
    "(?i).+@(.+\\.)*bk\\..+",
    "(?i).+@(.+\\.)*foxmail\\..+",
    "(?i).+@(.+\\.)*gmail\\..+",
    "(?i).+@(.+\\.)*hotmail\\..+",
    "(?i).+@(.+\\.)*icloud\\..+",
    "(?i).+@(.+\\.)*inbox\\..+",
    "(?i).+@(.+\\.)*live\\..+",
    "(?i).+@(.+\\.)*mail\\..+",
    "(?i).+@(.+\\.)*mailinator\\..+",
    "(?i).+@(.+\\.)*outlook\\..+",
    "(?i).+@(.+\\.)*proton\\..+",
    "(?i).+@(.+\\.)*qq\\..+",
    "(?i).+@(.+\\.)*rambler\\..+",
    "(?i).+@(.+\\.)*sina\\..+",
    "(?i).+@(.+\\.)*yeah\\..+",
    "(?i).+@(.+\\.)*yahoo\\..+",
    "(?i).+@(.+\\.)*yandex\\..+",
    "(?i).+@(.+\\.)*ecohealthalliance\\.org",
    "(?i).+@(.+\\.)+cn",
    "(?i).+@(.+\\.)+hk",
    "(?i).+@(.+\\.)+mo",
    "(?i).+@(.+\\.)+ru",
    "(?i).+@(.+\\.)+ir",
    "(?i).+@(.+\\.)+nk",
    "(?i).+@(.+\\.)+cu",
    "(?i).+@(.+\\.)+ve",
    "(?i)ahuff@msu\\.edu",
    "(?i)judite.salencia@ins\\.gov\\.mz",
    "(?i)kinleypenjor@fnph\\.edu\\.bt",
    "(?i)Nitish.debnath@cvasu\\.ac\\.bd",
    "(?i)peter.thompson@up\\.ac\\.za",
    "(?i)rostal@onehealthresearch\\.net",
    "(?i)S.dorjee@kgumsb\\.edu\\.bt",
    "(?i)SharminChowdhury@cvasu\\.ac\\.bd",
    "(?i)supaporn.wac@chula\\.ac\\.th",
    "(?i)thegroke@mac\\.com",
    "(?i)ydu@mrn\\.org",
  ]
}