package org.broadinstitute.dsde.firecloud.integrationtest

import java.text.SimpleDateFormat
import java.util.Calendar

import org.broadinstitute.dsde.firecloud.FireCloudConfig
import org.broadinstitute.dsde.firecloud.dataaccess._
import org.broadinstitute.dsde.firecloud.elastic.ElasticUtils
import org.broadinstitute.dsde.firecloud.model.LibrarySearchParams
import org.elasticsearch.action.support.WriteRequest.RefreshPolicy
import org.elasticsearch.client.transport.TransportClient

import scala.util.{Failure, Success, Try}

/**
  * Created by davidan on 2/9/17.
  */
object ESIntegrationSupport extends IntegrationTestConfig {

  // generate a unique, timestamped index name that is obvious to users it was generated by unit tests
  lazy val itTestIndexName = {
    val tag = "ittest"
    val timeStr = new SimpleDateFormat("yyyyMMdd't'HH:mm:ss").format(Calendar.getInstance.getTime)
    val username = Try(System.getProperty("user.name")) match {
      case Success(str) => str.toLowerCase
      case Failure(ex) => "unknownuser"
    }
    val hostname = Try(java.net.InetAddress.getLocalHost.getHostName) match {
      case Success(str) => str.toLowerCase
      case Failure(ex) => "unknownhostname"
    }

    Seq(tag, username, hostname, timeStr).mkString("_")
  }

  // construct a client, using IntegrationTestConfig's server names (which should be the runtime server names)
  lazy val client: TransportClient = ElasticUtils.buildClient(ITElasticSearch.servers, ITElasticSearch.clusterName)

  lazy val mockOntologyDAO:OntologyDAO = new MockOntologyDAO
  lazy val researchPurposeSupport:ResearchPurposeSupport = new ESResearchPurposeSupport(mockOntologyDAO)

  lazy val searchDAO:SearchDAO = {
    // use the temporary index name defined above
    new ElasticSearchDAO(client, itTestIndexName, researchPurposeSupport)
  }

  lazy val ontologyDAO:OntologyDAO = {
    // use the index name defined in reference.conf, since we execute read-only
    new ElasticSearchOntologyDAO(client, FireCloudConfig.ElasticSearch.ontologyIndexName)
  }

  lazy val shareLogDAO:ShareLogDAO = {
    new ElasticSearchShareLogDAO(client, itTestIndexName, RefreshPolicy.IMMEDIATE)
  }

  lazy val emptyCriteria = LibrarySearchParams(None,Map.empty[String,Seq[String]],None,Map.empty[String,Int],None,None,None,None)

}
