name: Elasticsearch Integration Tests

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ develop ]
  workflow_call:

jobs:
  es-integration-tests:
    name: Elasticsearch Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Start Elasticsearch
        run: ./docker/run-es.sh start

      - name: Execute Tests
        run: sbt it:test

