name: Trivy scan
on: [pull_request]

jobs:
  appsec-trivy:
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build jar
        run: |
          docker run --rm -e GIT_MODEL_HASH=${GITHUB_SHA:0:8} -v $PWD:/working -w /working \
            broadinstitute/scala-baseimage /working/src/docker/install.sh /working

      - uses: broadinstitute/dsp-appsec-trivy-action@v1
