name: Trivy scan
on: [pull_request]

jobs:
  appsec-trivy:
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # submodules: true

      - name: Build jar
        run: |
          set -ex
          echo ${BRANCH}
          git rev-parse --abbrev-ref HEAD
          git rev-parse --short origin/HEAD
          #./script/build.sh jar

      - uses: broadinstitute/dsp-appsec-trivy-action@v1
