name: Scala CI

on:
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    # coursier cache action caches both coursier and sbt caches
    - name: coursier-cache-action
      uses: coursier/cache-action@v6

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'sbt'

    - name: Run tests
      env:
        AGORA_URL_ROOT:  http://localhost:8989
        RAWLS_URL_ROOT: http://localhost:8990
        THURLOE_URL_ROOT: http://localhost:8991
        FIRE_CLOUD_ID: 123
      run: sbt clean coverage test coverageReport

    - uses: codecov/codecov-action@v4
      if: ${{ always() }}
